### ISSUE TITLE
How to write conf content in coding

### ISSUE THREAD

**Issue by baozengkai** [unipop-graph/unipop#109]
I would like to use tinkerpop connection elasticsearch, I have written a json configuration file, how should I add this configuration file to conf? The code did not talk about how to write conf on json configuration.

**Comment by seanbarzilay** [comment]
You need to create a configuration like so
```java
BaseConfiguration conf = new BaseConfiguration();
conf.addProperty('providers', '/path/to/mapping/folder');
UniGraph graph = UniGraph.open(conf);
```

**Comment by baozengkai** [comment]
@seanbarzilay 
    Thank you for your immediate reply. I write the above code on IDEA, as follows:
        BaseConfiguration conf = new BaseConfiguration();
        conf.addProperty("providers","/company/tinkerpop-server/json/");
        UniGraph graph=UniGraph.open(conf);
        GraphTraversalSource g=graph.traversal();
        System.out.println(g.V().key());
  and I copy your modern.json to my folder.but when I run the application,it told me this:
        org.json.JSONException: A JSONObject text must begin with '{' at character 1
  but I checked out the modern.json there is no character error,the modern.json is providered by this project,and I do not know how to do next?

**Comment by baozengkai** [comment]
@seanbarzilay
Thank you for your immediate reply. I wrote the above code on IDEA, as follows:
                    BaseConfiguration conf = new BaseConfiguration();
                    conf.addProperty("providers","/company/tinkerpop-server/json/");
                    UniGraph graph=UniGraph.open(conf);
                    GraphTraversalSource g=graph.traversal();
                    System.out.println(g.V().key());
  and I copy the modern.json to my folder.but When I run my application,It show me this:
         org.json.JSONException: A JSONObject text must begin with '{' at character 1
  I checked out the modern.json file .There is no character error.and the modern.json is provided by this project.so I don't how to do next? Look forward for your reply.

**Comment by seanbarzilay** [comment]
Do you maybe have another file in that folder which is not a JSON file?

**Comment by baozengkai** [comment]
It works! Because my folder has a hidden file, so I delete the hidden file, you can successfully mapped.thank you for your help!

**Comment by baozengkai** [comment]
It works! Because my folder has a hidden file, so when I delete the hidden file,  can successfully mapped.thank you for your help!
