### ISSUE TITLE
Documentation for unipop configuration / providers file

### ISSUE THREAD

**Issue by paul-k-civitas** [unipop-graph/unipop#113]
Where can I find information about what a provider file must contain, and what options are configurable? I'm specifically interested in the options for unipop-elastic, but I'm sure others would also be interested in available configuration parameters for the other connection plugins.

**Comment by seanbarzilay** [comment]
Hi @paul-k-civitas  do you need something beyond [Elastic Configuration](https://github.com/unipop-graph/unipop/wiki/Elastic-Configuration)?

**Comment by paul-k-civitas** [comment]
Ah, I always forget about the Wiki tab... This helps, but I was hoping for more information about what can go in the `properties` object nested within the vertex or edge description objects. I also know from some examples in the repository that one can set the `dynamicProperties` key in the vertex and edge objects; are there any other options one can set at this level, to control how Unipop works with Elasticsearch?

**Comment by seanbarzilay** [comment]
In the `properties` object you can map properties as shown in [Mapping properties](https://github.com/unipop-graph/unipop/wiki/Mapping-Properties) and beside `dynamicProperties` there aren't any more options from outside the `property` object as everything that is outside of it is basically a required property with the exception of `dymamicProperties`.

**Comment by paul-k-civitas** [comment]
That's everything I needed. Apologies for not digging a little deeper before creating this issue. Thanks for your prompt help.
