### ISSUE TITLE
Multi-schema tests

### ISSUE THREAD

**Issue by seanbarzilay** [unipop-graph/unipop#72]
Configure JUnit to run the test Suites multiple times, once for each schema configuration.
Also ignore tests that use graphs (Modern, Grateful, etc) that the schema doesn't support.

**Comment by seanbarzilay** [comment]
When this is done, we should configure an automatic build that runs all the tests.

**Comment by rmagen** [comment]
@seanbarzilay Why did you close this? Do we have an automatic build running?? :)

**Comment by seanbarzilay** [comment]
Thought there was a seperate issue for the automatic build

**Comment by rmagen** [comment]
Feel free to make one.
On 08/08/2016 14:49:47, sbarzilay <notifications@github.com> wrote:
Thought there was a seperate issue for the automatic build
