### ISSUE TITLE
CoalescePropertyScema

### ISSUE THREAD

**Issue by seanbarzilay** [unipop-graph/unipop#83]
A property schema that receives multiple property schemas and returns the first schema that returns a value

**Comment by rmagen** [comment]
Cool!

Get Outlook for iOS




On Mon, Aug 8, 2016 at 11:49 AM +0300, "sbarzilay" <notifications@github.com> wrote:












A property schema that receives multiple property schemas and returns the first schema that returns a value

**Comment by seanbarzilay** [comment]
Maybe think of a more elegant way to initialize other than:
```json
...
"coalesce": true,
...
```
